# Generated by Django 4.2.11 on 2024-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook_app", "0002_alter_guestbookentry_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guestbookentry",
            old_name="name",
            new_name="user",
        ),
    ]
